### ISSUE TITLE
demo.py  ModuleNotFoundError: No module named 'pcdet.datasets.argo2.argo2_utils'

### ISSUE THREAD

**Issue by Zixiu99** [open-mmlab/OpenLidarPerceptron#1617]
Traceback (most recent call last):
  File "demo.py", line 18, in <module>
    from pcdet.datasets import DatasetTemplate
  File "/home/zixiu/anaconda3/envs/openpcdet/lib/python3.8/site-packages/pcdet-0.6.0+255db8f-py3.8-linux-x86_64.egg/pcdet/datasets/__init__.py", line 15, in <module>
    from .argo2.argo2_dataset import Argo2Dataset
  File "/home/zixiu/anaconda3/envs/openpcdet/lib/python3.8/site-packages/pcdet-0.6.0+255db8f-py3.8-linux-x86_64.egg/pcdet/datasets/argo2/argo2_dataset.py", line 15, in <module>
    from .argo2_utils.so3 import yaw_to_quat, quat_to_yaw
ModuleNotFoundError: No module named 'pcdet.datasets.argo2.argo2_utils'

I encountered this error while trying to run the demo. I have tried rerunning python setup.py develop, but it still hasn't resolved the issue.

**Comment by Zixiu99** [comment]
To resolve the issue, replace the pcdet folder in /home/zixiu/anaconda3/envs/openpcdet_copy/lib/python3.8/site-packages/pcdet-0.6.0+255db8f-py3.8-linux-x86_64.egg/pcdet with the pcdet folder from the project.
