### ISSUE TITLE
INSTALL ERROR: python3 setup.py develop

### ISSUE THREAD

**Issue by oulton** [open-mmlab/OpenLidarPerceptron#1651]
**I checkout the branch to v0.5.0, then run 'python3 setup.py develop'. error:**

[1/7] c++ -MMD -MF /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/voxel_query.o.d -pthread -B /home/hyper/anaconda3/envs/pcdet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/TH -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/hyper/anaconda3/envs/pcdet/include/python3.8 -c -c /data/hyper/code/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/src/voxel_query.cpp -o /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/voxel_query.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=pointnet2_stack_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
**FAILED**: /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/voxel_query.o 
c++ -MMD -MF /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/voxel_query.o.d -pthread -B /home/hyper/anaconda3/envs/pcdet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/TH -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/hyper/anaconda3/envs/pcdet/include/python3.8 -c -c /data/hyper/code/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/src/voxel_query.cpp -o /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/voxel_query.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=pointnet2_stack_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/data/hyper/code/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/src/voxel_query.cpp:3:10: fatal error: THC/THC.h: No such file or directory
 #include <THC/THC.h>
          ^~~~~~~~~~~
compilation terminated.
[2/7] c++ -MMD -MF /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/ball_query.o.d -pthread -B /home/hyper/anaconda3/envs/pcdet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/TH -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/hyper/anaconda3/envs/pcdet/include/python3.8 -c -c /data/hyper/code/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/src/ball_query.cpp -o /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/ball_query.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=pointnet2_stack_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
**FAILED**: /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/ball_query.o 
c++ -MMD -MF /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/ball_query.o.d -pthread -B /home/hyper/anaconda3/envs/pcdet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/TH -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/hyper/anaconda3/envs/pcdet/include/python3.8 -c -c /data/hyper/code/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/src/ball_query.cpp -o /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/ball_query.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=pointnet2_stack_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/data/hyper/code/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/src/ball_query.cpp:10:10: fatal error: THC/THC.h: No such file or directory
 #include <THC/THC.h>
          ^~~~~~~~~~~
compilation terminated.
[3/7] c++ -MMD -MF /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/interpolate.o.d -pthread -B /home/hyper/anaconda3/envs/pcdet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/TH -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/hyper/anaconda3/envs/pcdet/include/python3.8 -c -c /data/hyper/code/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/src/interpolate.cpp -o /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/interpolate.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=pointnet2_stack_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
**FAILED**: /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/interpolate.o 
c++ -MMD -MF /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/interpolate.o.d -pthread -B /home/hyper/anaconda3/envs/pcdet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/TH -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/hyper/anaconda3/envs/pcdet/include/python3.8 -c -c /data/hyper/code/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/src/interpolate.cpp -o /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/interpolate.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=pointnet2_stack_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/data/hyper/code/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/src/interpolate.cpp:10:10: fatal error: THC/THC.h: No such file or directory
 #include <THC/THC.h>
          ^~~~~~~~~~~
compilation terminated.
[4/7] c++ -MMD -MF /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/group_points.o.d -pthread -B /home/hyper/anaconda3/envs/pcdet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/TH -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/hyper/anaconda3/envs/pcdet/include/python3.8 -c -c /data/hyper/code/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/src/group_points.cpp -o /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/group_points.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=pointnet2_stack_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
**FAILED**: /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/group_points.o 
c++ -MMD -MF /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/group_points.o.d -pthread -B /home/hyper/anaconda3/envs/pcdet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/TH -I/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/hyper/anaconda3/envs/pcdet/include/python3.8 -c -c /data/hyper/code/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/src/group_points.cpp -o /data/hyper/code/OpenPCDet/build/temp.linux-x86_64-cpython-38/pcdet/ops/pointnet2/pointnet2_stack/src/group_points.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1013"' -DTORCH_EXTENSION_NAME=pointnet2_stack_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/data/hyper/code/OpenPCDet/pcdet/ops/pointnet2/pointnet2_stack/src/group_points.cpp:12:10: fatal error: THC/THC.h: No such file or directory
 #include <THC/THC.h>
          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/hyper/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "/home/hyper/anaconda3/envs/pcdet/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by Petros626** [comment]
@oulton  https://github.com/open-mmlab/OpenPCDet/issues/1668#issuecomment-2376843239
